version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: supahealth_db_prod
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: supahealth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - supahealth_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  app:
    build: .
    container_name: supahealth_app_prod
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/supahealth
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - supahealth_network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

volumes:
  postgres_data:
    name: supahealth_postgres_data_prod

networks:
  supahealth_network:
    name: supahealth_network_prod 