"""Initial migration with email as primary key and composite heart rate key

Revision ID: 21bdc888bd06
Revises: 
Create Date: 2025-09-05 19:21:15.141998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21bdc888bd06'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('hourly_heart_rate',
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('min_hr', sa.Integer(), nullable=True),
    sa.Column('avg_hr', sa.Numeric(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('avg_hr IS NULL OR (avg_hr >= 0 AND avg_hr <= 300)', name='hourly_heart_rate_avg_hr_check'),
    sa.CheckConstraint('max_hr IS NULL OR (max_hr >= 0 AND max_hr <= 300)', name='hourly_heart_rate_max_hr_check'),
    sa.CheckConstraint('min_hr IS NULL OR (min_hr >= 0 AND min_hr <= 300)', name='hourly_heart_rate_min_hr_check'),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('user_email', 'date', 'source')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hourly_heart_rate')
    op.drop_table('users')
    # ### end Alembic commands ###
