"""Create nutrition and chat tables

Revision ID: d4f654223e61
Revises: 3753f108ec9a
Create Date: 2025-11-05 18:23:57.418611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4f654223e61'
down_revision: Union[str, Sequence[str], None] = '3753f108ec9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('calories', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protein', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('carbs', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('serving_unit', sa.String(), nullable=True),
    sa.Column('serving_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    op.create_table('consumption_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('food_id', sa.String(), nullable=False),
    sa.Column('servings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('serving_unit', sa.String(), nullable=True),
    sa.Column('calories_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protein_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('carbs_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fat_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('calories_total >= 0', name='check_calories_total_non_negative'),
    sa.CheckConstraint('carbs_total >= 0', name='check_carbs_total_non_negative'),
    sa.CheckConstraint('fat_total >= 0', name='check_fat_total_non_negative'),
    sa.CheckConstraint('protein_total >= 0', name='check_protein_total_non_negative'),
    sa.CheckConstraint('servings > 0', name='check_servings_positive'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consumption_logs_food_id'), 'consumption_logs', ['food_id'], unique=False)
    op.create_index(op.f('ix_consumption_logs_id'), 'consumption_logs', ['id'], unique=False)
    op.create_index(op.f('ix_consumption_logs_is_saved'), 'consumption_logs', ['is_saved'], unique=False)
    op.create_index(op.f('ix_consumption_logs_logged_at'), 'consumption_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_consumption_logs_user_id'), 'consumption_logs', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    op.drop_index(op.f('ix_activity_steps_id'), table_name='activity_steps')
    op.alter_column('activity_workouts', 'source',
               existing_type=postgresql.ENUM('APPLE_WATCH', 'FITBIT', 'GARMIN', 'SAMSUNG', 'GOOGLE_FIT', 'STRAVA', 'MANUAL', 'OTHER', name='datasource'),
               nullable=False)
    op.add_column('nutrition_macros', sa.Column('food_name', sa.String(), nullable=False))
    op.add_column('nutrition_macros', sa.Column('is_saved', sa.Boolean(), nullable=False))
    op.alter_column('nutrition_macros', 'calories',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_column('nutrition_macros', 'meal_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrition_macros', sa.Column('meal_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('nutrition_macros', 'calories',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('nutrition_macros', 'is_saved')
    op.drop_column('nutrition_macros', 'food_name')
    op.alter_column('activity_workouts', 'source',
               existing_type=postgresql.ENUM('APPLE_WATCH', 'FITBIT', 'GARMIN', 'SAMSUNG', 'GOOGLE_FIT', 'STRAVA', 'MANUAL', 'OTHER', name='datasource'),
               nullable=True)
    op.create_index(op.f('ix_activity_steps_id'), 'activity_steps', ['id'], unique=False)
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_consumption_logs_user_id'), table_name='consumption_logs')
    op.drop_index(op.f('ix_consumption_logs_logged_at'), table_name='consumption_logs')
    op.drop_index(op.f('ix_consumption_logs_is_saved'), table_name='consumption_logs')
    op.drop_index(op.f('ix_consumption_logs_id'), table_name='consumption_logs')
    op.drop_index(op.f('ix_consumption_logs_food_id'), table_name='consumption_logs')
    op.drop_table('consumption_logs')
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
